#!/usr/bin/env node
import { readFile } from "node:fs/promises";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import chalk from "chalk";
import { Command } from "commander";
import { auditLibrary } from "./audit";
import { parseRekordboxXml } from "./rekordbox";
import { renderConsoleSummary, writeReport, type ReportFormat } from "./report";
import { renderSetPlan } from "./setPlan";

const program = new Command();

program
  .name("rb-amigo")
  .description("Safe Rekordbox XML audit, tagging, and set-prep assistant for DJs.")
  .version("0.1.0");

program
  .command("audit")
  .description("Audit a Rekordbox XML export without modifying Rekordbox or music files.")
  .requiredOption("--xml <path>", "Path to Rekordbox XML export")
  .option("--out <path>", "Report output path")
  .option("--format <format>", "json or markdown", "markdown")
  .action(async (options: { xml: string; out?: string; format: ReportFormat }) => {
    const audit = await runAudit(options.xml);
    output.write(chalk.green("Rekordbox Amigo audit complete.\n"));
    output.write(renderConsoleSummary(audit));

    if (options.out) {
      await writeReport(audit, options.out, options.format);
      output.write(chalk.cyan(`\nReport written to ${options.out}\n`));
    }
  });

program
  .command("tags")
  .description("Read a JSON audit and print suggested tagging priorities.")
  .requiredOption("--audit <path>", "Path to JSON audit generated by rb-amigo")
  .action(async (options: { audit: string }) => {
    const audit = JSON.parse(await readFile(options.audit, "utf8")) as Awaited<ReturnType<typeof runAudit>>;
    const top = audit.findings.slice(0, 20);
    output.write(chalk.bold("Tagging priority queue\n\n"));
    for (const finding of top) {
      output.write(`${chalk.cyan(finding.artist)} - ${finding.name}\n`);
      for (const suggestion of finding.suggestions) {
        output.write(`  - ${suggestion}\n`);
      }
      output.write("\n");
    }
  });

program
  .command("set-plan")
  .description("Turn an audit into a chapter-based set preparation prompt.")
  .requiredOption("--audit <path>", "Path to JSON audit generated by rb-amigo")
  .option("--hours <number>", "Set length in hours", "2")
  .option("--context <text>", "Set context, e.g. afterhours, festival, warmup", "club")
  .action(async (options: { audit: string; hours: string; context: string }) => {
    const audit = JSON.parse(await readFile(options.audit, "utf8")) as Awaited<ReturnType<typeof runAudit>>;
    output.write(renderSetPlan(audit, Number(options.hours), options.context));
  });

program
  .command("amigo")
  .description("Start a small conversational guide for library work.")
  .action(async () => {
    const rl = readline.createInterface({ input, output });
    output.write(chalk.bold("Rekordbox Amigo\n"));
    output.write("Tell me what you want to do. Try: audit, tags, set, or quit.\n\n");

    while (true) {
      const answer = (await rl.question(chalk.cyan("amigo> "))).trim().toLowerCase();
      if (["q", "quit", "exit"].includes(answer)) break;
      if (answer.includes("audit")) {
        output.write("Run: rb-amigo audit --xml ./rekordbox.xml --format markdown --out ./reports/library-audit.md\n");
      } else if (answer.includes("tag")) {
        output.write("Run an audit as JSON first, then: rb-amigo tags --audit ./reports/library-audit.json\n");
      } else if (answer.includes("set")) {
        output.write("Run: rb-amigo set-plan --audit ./reports/library-audit.json --hours 3 --context afterhours\n");
      } else {
        output.write("I can help with audits, tag cleanup, and chapter-based set prep. Start with an XML audit.\n");
      }
    }

    rl.close();
  });

async function runAudit(xmlPath: string) {
  const library = await parseRekordboxXml(xmlPath);
  return auditLibrary(library, xmlPath);
}

program.parseAsync().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  output.write(chalk.red(`Error: ${message}\n`));
  process.exitCode = 1;
});
